# Dockerfile with tensorflow gpu support on python3, pandas, matplotlib,
# pydot and tensorflow-addons while using GPU enhancement
FROM tensorflow/tensorflow:2.3.1

LABEL Name=is-coffee-wet \
      Version=0.0.1

RUN pip install \
      matplotlib==3.3.2 \
      pandas==1.1.3 \
      tensorflow-addons==0.11.2

WORKDIR /data

VOLUME ["/data/neural-network"]

CMD ["python3", "IsCoffeeWet/top_level.py"]

COPY . ./
